contest/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
# from django.views.generic import RedirectView
from . import settings
from .forms import BootstrapAuthenticationForm, BootstrapPasswordChangeForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',
         auth_views.LoginView.as_view(
             authentication_form=BootstrapAuthenticationForm, redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/',
         auth_views.PasswordChangeView.as_view(
             form_class=BootstrapPasswordChangeForm),
         name='password_change'),
    path('change-password/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('round.urls')),
    # path('round-two/', include('round.urls')),
    # path('', RedirectView.as_view(url='round-two/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

round/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('countdown-json', views.countdown_json, name='countdown_json'),
    path('submission-not-open/', views.submission_not_open, name='submission_not_open'),
    path('problems/', views.ProblemListView.as_view(), name='problems'),
    path('submission/', views.SubmissionSummaryView.as_view(), name='submission_summary'),
    path('submit/<int:problem_number>/', views.submit_sol_for_problem, name='submit_sol_for_problem'),
    path('submission-statistics/', views.submission_statistics, name='submission_statistics'),
    path('contestants/', views.ContestantListView.as_view(), name='contestants'),
    path('contestant/<int:pk>', views.ContestantDetailView.as_view(), name='contestant_details'),
    path('contact-us', views.contact_us, name='contact_form'),
    # can also use regular expression, see
    # https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#URL_mapping_2
]

round/models.py
from datetime import datetime
from hashlib import sha3_256
import struct
from django.db import models
from django.conf import settings
from django.core import validators
from django.utils.translation import gettext_lazy
from django.urls import reverse

# Create your models here.


class Contestant(models.Model):
    contestant_id = models.AutoField(
        primary_key=True,
        editable=False,
        verbose_name='Contestant ID',
    )
    contestant_user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
    )

    class Meta:
        ordering = ['contestant_id']

    @property
    def first_name(self):
        if self.contestant_user:
            return self.contestant_user.first_name
        return ''

    @property
    def last_name(self):
        if self.contestant_user:
            return self.contestant_user.last_name
        return ''

    @property
    def fl_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.contestant_id} ({self.fl_name})'

    def get_absolute_url(self):
        return reverse('contestant_details', args=[str(self.contestant_id)])


class Problem(models.Model):
    number = models.AutoField(
        primary_key=True,
    )
    prompt = models.TextField(
        blank=True,
    )

    class Meta:
        ordering = ['number']

    def __str__(self):
        return f'Problem {self.number}'

    def get_absolute_url(self):
        return reverse('problem-details', args=[str(self.number)])


def contestant_problem_path(instance, filename):
    # del filename
    cid = instance.contestant.contestant_id
    m = sha3_256()
    m.update(instance.contestant.fl_name.encode('utf-8'))
    m.update(struct.pack('>f', datetime.now().timestamp()))
    m.update(struct.pack('>i', instance.contestant.contestant_id))
    # Return an obfuscated path relative to MEDIA_ROOT
    return f'uploads/{cid}/{instance.problem.number}/{m.hexdigest()}/{filename}'


class Submission(models.Model):
    contestant = models.ForeignKey(
        Contestant,
        on_delete=models.SET_NULL,
        null=True,
        editable=False,
        related_name='submissions',
    )
    problem = models.ForeignKey(
        Problem,
        on_delete=models.SET_NULL,
        null=True,
        editable=False,
        related_name='submissions',
    )
    # In case of contestant/problem deletion,
    # use contestant.contestant_id * 10 + problem.number as a fallback
    # Assumes problem.number < 10
    fallback_number = models.IntegerField(
        editable=False,
        validators=[validators.MinValueValidator(2000000),
                    validators.MaxValueValidator(9999999)],
    )
    solution = models.FileField(
        upload_to=contestant_problem_path,
        max_length=140,
    )
    submission_time = models.DateTimeField(
        null=True,
    )

    class Status(models.TextChoices):
        NOT_ATTEMPTED = 'DNA', gettext_lazy('Not Attempted')
        ATTEMPTED = 'ATT', gettext_lazy('Attempted')
        MARKED = 'MKD', gettext_lazy('Marked')

    status = models.CharField(
        max_length=3,
        choices=Status.choices,
        default=Status.NOT_ATTEMPTED,
    )

    class Meta:
        ordering = ['contestant', 'problem']
        permissions = [('submit_solutions', 'Can submit solutions'),
                       ('mark_solutions', 'Can mark solutions')]

    # def contestant_id(self):
    #     return self.contestant.contestant_id
    # contestant_id.short_description = 'Contestant ID'
    # contestant_id.admin_order_field = 'contestant_id'

    def __str__(self):
        if self.contestant is None or self.problem is None:
            return f'Submission (fallback number: {self.fallback_number})'
        return f'Submission for {self.problem} by {self.contestant.contestant_id}'

round/forms.py
from upload_validator import FileTypeValidator

from django import forms
# from django.utils.html import escape
# from django.core.exceptions import ValidationError
# from django.utils.translation import ugettext_lazy as _


class SubmitForProblemForm(forms.Form):
    solution = forms.FileField(
        required=True,
        max_length=40,
        help_text='Upload your solution (PDF only; size up to 5 MB; '
                  + 'file name up to 40 characters long)',
        # allow_empty_file=False,
        widget=forms.FileInput(
            attrs={'id': 'solutionInput',
                   'class': 'form-control',
                   'accept': '.pdf,application/pdf'}
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.has_error('solution'):
            self.fields['solution'].widget.attrs.update({
                'class': 'form-control is-invalid',
                'aria-describedby': 'solutionValidationFeedback'
            })

    def clean_solution(self):
        file = self.cleaned_data['solution']
        # if not file.name.endswith('.pdf'):
        #     raise ValidationError(
        #         _('The extension of the file is not \'.pdf\'.'),
        #         code='invalid'
        #     )

        # Use django-upload-validator for file validation
        # It checks the extension and MIME type of an uploaded file
        # inferred from the file name and the binary signature / magic number
        # using python-magic, which in turn uses the libmagic C library
        validator = FileTypeValidator(
            allowed_types=['application/pdf'],
            allowed_extensions=['.pdf']
        )
        # with file.open() as file_resource:
        file_resource = file.open()
        validator(file_resource)
        return file


class ContactForm(forms.Form):
    email = forms.EmailField(
        required=True,
        help_text='The email address you would like us to send our response to',
    )
    subject = forms.ChoiceField(
        required=True,
        choices=[
            ('paper', 'Contest paper'),
            ('website', 'Website'),
            ('other', 'Other')
        ],
    )
    message = forms.CharField(
        required=True,
        min_length=5,
        strip=True,
        widget=forms.Textarea,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        input_classes = {
            'email': 'form-control',
            'subject': 'form-select',
            'message': 'form-control'
        }

        for field_name in ('email', 'subject', 'message'):
            if not self.has_error(field_name):
                self.fields[field_name].widget.attrs.update({
                    'class': input_classes[field_name],
                })
            else:
                self.fields[field_name].widget.attrs.update({
                    'class': input_classes[field_name] + ' is-invalid',
                    'aria-describedby': field_name + 'ValidationFeedback'
                })

    # def clean_message(self):
    #     return escape(self.cleaned_data['message'])

round/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse  # HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, DetailView

from .forms import SubmitForProblemForm, ContactForm
from .models import Contestant, Problem, Submission
from . import time_status, webhooks

# Create your views here.


def index(request):
    """View function for home page of site."""
    if request.user.is_authenticated:
        return render(request, 'round/index.html')

    return render(request, 'landing.html')


def countdown_json(request):
    """Handles a request for the amount time of left."""
    time_left = time_status.get_millisec_time_until_start()
    if time_left > 0:
        description = 'until Round Two starts'
        enable = True
    else:
        time_left = time_status.get_millisec_time_until_end()
        if time_left > 0:
            description = 'until Round Two ends'
            enable = True
        else:
            time_left = -1
            round_status = time_status.get_round_status()
            if round_status == time_status.RoundStatus.EXTRA_SUBMISSION_TIME:
                description = 'Submission will close soon'
            elif round_status == time_status.RoundStatus.EMBARGO_IN_PLACE:
                description = 'The embargo is still in place'
            else:
                description = 'Round Two has ended'
            enable = False
    return JsonResponse({
        'timeLeft': time_left,
        'enable': enable,
        'description': description
    })
    # return HttpResponse('%d' % time_status.get_millisec_time(), content_type='text/plain')


class ContestantListView(PermissionRequiredMixin, ListView):
    model = Contestant
    permission_required = 'round.mark_solutions'
    paginate_by = 10
    # for more customisations such as template variable name, more context data
    # https://docs.djangoproject.com/en/3.1/topics/class-based-views/generic-display/
    # https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#View_class-based
    # https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#Views


class ContestantDetailView(PermissionRequiredMixin, DetailView):
    model = Contestant
    permission_required = 'round.mark_solutions'


class ProblemListView(LoginRequiredMixin, ListView):
    model = Problem

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reveal'] = time_status.round_has_started()
        return context


class SubmissionSummaryView(PermissionRequiredMixin, ListView):
    model = Submission
    permission_required = 'round.submit_solutions'
    template_name = 'round/submission_summary.html'

    # Alternatively, with UserPassesTestMixin
    # def test_func(self):
    #     return self.request.user.groups.filter(name='Participants').exists()

    def get_queryset(self):
        # ISSUE: What if the user has not been associated with a Contestant object?
        return self.request.user.contestant.submissions.order_by('problem__number')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['submission_open'] = time_status.submission_is_open()
        return context


@login_required
@permission_required('round.submit_solutions', raise_exception=True)
def submit_sol_for_problem(request, problem_number):
    submission = get_object_or_404(
        Submission,
        contestant__contestant_user=request.user,
        problem__number=problem_number
    )

    if not time_status.submission_is_open():
        return HttpResponseRedirect(reverse('submission_not_open'))

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        submission_time = time_status.get_datetime()

        # Create a form instance and populate it with data from the request (binding):
        form = SubmitForProblemForm(request.POST, request.FILES)

        # Check if the form is valid:
        if form.is_valid():
            # submission.solution = form.cleaned_data['solution']
            submission.solution.delete(save=False)
            submission.solution = request.FILES['solution']
            submission.status = Submission.Status.ATTEMPTED
            submission.submission_time = submission_time
            submission.save()

            # ISSUE: What if submitted after being marked

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('submission_summary'))

    # If this is a GET (or any other method) create the default form.
    else:
        form = SubmitForProblemForm()
        # form = SubmitForProblemForm(initial={
        #     'solution': submission.solution,
        # })

    context = {
        'form': form,
        'submission': submission,
    }

    return render(request, 'round/submit_sol_for_problem.html', context)


def submission_not_open(request):
    return render(request, 'round/submission_not_open.html')


def submission_statistics(request):
    """View function for the submission statistics page."""

    # Generate counts of some of the main objects
    num_contestants = Contestant.objects.exclude(
        contestant_id__lte=200009).count()
    attempts = Submission.objects.exclude(
        status=Submission.Status.NOT_ATTEMPTED
    ).exclude(
        contestant__contestant_id__lte=200009
    )
    num_attempts = [(p, attempts.filter(problem__number=p).count())
                    for p in range(1, 5)]  # hard-coded for speed

    context = {
        'num_contestants': num_contestants,
        'num_attempts': num_attempts,
    }

    # Render the HTML template submission_statistics.html with the data in the context variable
    return render(request, 'round/submission_statistics.html', context=context)


@login_required
def contact_us(request):
    """View function for the contact form page."""

    could_not_send = False

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            # ISSUE: hard-coded at two places (the other is round/forms.py)
            subject_choices = {
                'paper': 'Contest paper',
                'website': 'Website',
                'other': 'Other'
            }

            user_is_contestant = Contestant.objects.filter(contestant_user=request.user).exists()
            if user_is_contestant:
                contestant = request.user.contestant
                author = f'{contestant.fl_name} ({contestant.contestant_id})'
            else:
                author = f'{request.user.first_name} {request.user.last_name}'
            email = form.cleaned_data['email']
            subject = subject_choices[form.cleaned_data['subject']]
            webhook_message = f'Subject: **{subject}**\nReply at: {email}\n\n' + \
                '> ' + form.cleaned_data['message'].replace('\n', '\n> ')

            could_not_send = not webhooks.send_message(author, webhook_message)

            if not could_not_send:
                return render(request, 'round/contact_form_sent.html')

    else:
        form = ContactForm(initial={
            'email': request.user.email,
        })

    context = {
        'form': form,
        'could_not_send': could_not_send,
    }

    return render(request, 'round/contact_form.html', context)

templates/round/base.html
{% extends "base_generic.html" %}

{% block title %}{% block head_title %}{% endblock %} - Cambridge Integration Bee{% endblock %}

{% block navbar %}
{% include "./navbar.html" %}
{% endblock %}

{% block main %}
<div class="row g-4">
    <div class="col-lg-9">
        <h1 class="mb-3">{% block content_title %}{% endblock %}</h1>

        {% block content %}{% endblock %}

        {% if is_paginated %}
        <div class="mt-3">
            {% include 'pagination.html' %}
        </div>
        {% endif %}
    </div>
    <div class="col-lg-3 pt-lg-3">
        {% include "./clock.html" %}
    </div>
</div>
{% endblock %}

templates/round/clock.html
<div id="clockDisplay" class="bg-gradient pt-2 pb-3 px-3">
    <div id="liveClock">
        <span id="liveClockHours">
            <span id="liveClockHoursNumber" class="fs-1"></span><span id="liveClockHoursUnit" class="fs-3">h </span>
        </span>
        <span id="liveClockMinutes">
            <span id="liveClockMinutesNumber" class="fs-1"></span><span id="liveClockMinutesUnit" class="fs-3">m </span>
        </span>
        <span id="liveClockSeconds">
            <span id="liveClockSecondsNumber" class="fs-1"></span><span id="liveClockSecondsUnit" class="fs-3">s </span>
        </span>
    </div>
    <div id="liveClockDescription"></div>
</div>

{% load static %}
<script src="{% static 'javascript/round/clock.js' %}"></script>

templates/round/contact_form.html
{% extends "./base.html" %}

{% block head_title %}Contact us{% endblock %}
{% block content_title %}Contact us{% endblock %}

{% block content %}

{% if could_not_send %}
<div class="mb-3 alert alert-danger" role="alert">
    An error occurred while trying to send your message.
    Please try again or <a href="mailto:contest@icmathscomp.org" class="alert-link">contact us by email</a> instead.
</div>
{% endif %}

<form action="" method="post" onsubmit="disableSendInput()">
    {% csrf_token %}

    <div class="mb-3">
        <label for="{{ form.email.id_for_label }}" class="form-label">{{ form.email.label }}</label>
        {{ form.email }}
        <div class="form-text">{{ form.email.help_text }}</div>
        {% if form.email.errors %}
        <div id="emailValidationFeeback" class="invalid-feedback">
            <ul class="list-unstyled mb-0">
                {% for error in form.email.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>

    <div class="mb-3">
        <label for="{{ form.subject.id_for_label }}" class="form-label">{{ form.subject.label }}</label>
        {{ form.subject }}
        <div class="form-text">{{ form.subject.help_text }}</div>
        {% if form.subject.errors %}
        <div id="subjectValidationFeeback" class="invalid-feedback">
            <ul class="list-unstyled mb-0">
                {% for error in form.subject.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>

    <div class="mb-3">
        <label for="{{ form.message.id_for_label }}" class="form-label">{{ form.message.label }}</label>
        {{ form.message }}
        <div class="form-text">{{ form.message.help_text }}</div>
        {% if form.message.errors %}
        <div id="messageValidationFeeback" class="invalid-feedback">
            <ul class="list-unstyled mb-0">
                {% for error in form.message.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>

    {% if form.non_field_errors %}
    <div class="mb-3 text-danger">
        <ul class="list-unstyled mb-0">
            {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <div class="row">
        <div class="col-md-3">
            <input type="submit" id="sendInput" class="btn btn-primary w-100" value="Send">
        </div>
    </div>
</form>

<script>
    function disableSendInput() {
        var input = document.getElementById('sendInput');
        input.disabled = true;
        input.value = 'Sending...';
    }
</script>

{% endblock %}

templates/round/contact_form_sent.html
{% extends "./base.html" %}

{% block head_title %}Contact us{% endblock %}
{% block content_title %}Contact us{% endblock %}

{% block content %}
Your message has been sent. We will get in touch shortly.
{% endblock %}

templates/round/contestant_detail.html
{% extends "./base.html" %}

{% block head_title %}Contestant: {{ contestant.fl_name }}{% endblock %}
{% block content_title %}Contestant: {{ contestant.fl_name }}{% endblock %}

{% block content %}

<p><strong>Contestant ID:</strong> {{ contestant.contestant_id }}</p>

<div>
    <h4>Submissions</h4>

    {% for submission in contestant.submissions.all %}
    <hr>
    <p class="
        {% if submission.status == submission.Status.ATTEMPTED %}
            text-warning
        {% elif submission.status == submission.Status.MARKED %}
            text-success
        {% else %}
            text-muted
        {% endif %}">
        {{ submission.get_status_display }}
    </p>
    <p><strong>Problem:</strong> {{ submission.problem.number }}</p>
    {% if submission.status != 'DNA' %}
    <p class="text-muted"><strong>Submission time:</strong> {{ submission.submission_time }}</p>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}

templates/round/contestant_list.html
{% extends "./base.html" %}

{% block head_title %}Contestant List{% endblock %}
{% block content_title %}Contestant List{% endblock %}

{% block content %}

{% if contestant_list %}
<ul>
    {% for contestant in contestant_list %}
    <li>
        ({{contestant.contestant_id}}) <a href="{{ contestant.get_absolute_url }}">{{ contestant.fl_name }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no contestants in this round.</p>
{% endif %}

{% endblock %}

templates/round/navbar.html
{% extends "navbar.html" %}

{% load static %}



{% block navbar_nav %}
{% if user.is_authenticated %}
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
    {% if user.is_staff %}
    <li class="nav-item">
        {% if "/admin/" in request.path %}
        <a class="nav-link active" href="/admin">Admin</a>
        {% else %}
        <a class="nav-link" href="/admin">Admin</a>
        {% endif %}
    </li>
    {% endif %}

    <li class="nav-item">
        {% if "/problems/" in request.path %}
        <a class="nav-link active" href="{% url 'problems' %}">Problems</a>
        {% else %}
        <a class="nav-link" href="{% url 'problems' %}">Problems</a>
        {% endif %}
    </li>

    {% if perms.round.submit_solutions and not user.is_superuser %}
    <li class="nav-item">
        {% if "/submission/" in request.path or "/submit/" in request.path %}
        <a class="nav-link active" href="{% url 'submission_summary' %}">Submission</a>
        {% else %}
        <a class="nav-link" href="{% url 'submission_summary' %}">Submission</a>
        {% endif %}
    </li>
    {% endif %}

    {% if perms.round.mark_solutions %}
    <li class="nav-item">
        {% if "/submission-statistics/" in request.path %}
        <a class="nav-link active" href="{% url 'submission_statistics' %}">Statistics</a>
        {% else %}
        <a class="nav-link" href="{% url 'submission_statistics' %}">Statistics</a>
        {% endif %}
    </li>

    <li class="nav-item">
        {% if "/contestants/" in request.path or "/contestant/" in request.path %}
        <a class="nav-link active" href="{% url 'contestants' %}">Contestants</a>
        {% else %}
        <a class="nav-link" href="{% url 'contestants' %}">Contestants</a>
        {% endif %}
    </li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

templates/round/problem_list.html
{% extends "./base.html" %}

{% block head_title %}Problems{% endblock %}
{% block content_title %}Problems{% endblock %}

{% block content %}

{% if not reveal %}

<p>The problems will be shown here once Round Two starts.</p>

<p>A PDF version of the contest paper will also be available for download.</p>

{% endif %}

{% if reveal or perms.round.mark_solutions %}

{% if perms.round.mark_solutions and not reveal %}
<p><em>The remainder of the page is visible to markers only:</em></p>
{% endif %}

<p>Download the PDF: <a
        href="/media/paper/130dee6ee428cc9d9c7b87098c3c427f354e1dd0d36456b13a7c0bd899f9dd07/ICMC_4_2_Paper.pdf">ICMC_4_2_Paper.pdf</a>
</p>

{% for problem in problem_list %}
<div class="mb-4">
    <h4>{{ problem }}</h4>
    {{ problem.prompt|safe }}
</div>
{% endfor %}

<!-- MathJax -->
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

{% endif %}

{% endblock %}

templates/round/submission_not_open.html
{% extends "./base.html" %}

{% block head_title %}Submission not open{% endblock %}
{% block content_title %}Submission not open{% endblock %}

{% block content %}

<p>If you have been redirected to this page, it is likely because either Round Two has not started or submission has already closed.</p>

<p>If you believe you are seeing this page in error, try following the links on the <a href="{% url 'submission_summary' %}">submission summary page</a>. Should the problem persist, please contact us using the details provided on the homepage.</p>

<a href="{% url 'index' %}">Home</a>

{% endblock %}

templates/round/submission_summary.html
{% extends "./base.html" %}

{% block head_title %}Submission summary{% endblock %}
{% block content_title %}Submission summary{% endblock %}

{% block content %}

<p><strong>Contestant ID</strong>: {{ user.contestant.contestant_id }}</p>
<p><strong>Name</strong>: {{ user.contestant.fl_name }}</p>

{% if not submission_open %}
<p>When submission is open, links for uploading solutions will be available in the table below.</p>
{% endif %}

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Problem</th>
                <th>Status</th>
                <th>Submission time (GMT)</th>
                <th>Action(s)</th>
            </tr>
        </thead>
        <tbody>
            {% for submission in submission_list %}
            <tr>
                <th style="text-align: center;">{{ submission.problem.number }}</td>
                    <!-- ISSUE: avoid hard-coded status checks? -->
                <td class="
                    {% if submission.status == submission.Status.NOT_ATTEMPTED %}
                        text-warning
                    {% elif submission.status == submission.Status.ATTEMPTED %}
                        text-success
                    {% else %}
                        text-body
                    {% endif %}">
                    {{ submission.get_status_display }}
                </td>
                <td>{{ submission.submission_time|date:"d N Y, H:i:s"|default:"--" }}</td>
                <td>
                    {% if submission.status != 'DNA' %}<a href="{{ submission.solution.url }}" target="_blank">View
                        submission</a>{% endif %}
                    {% if submission_open %}<a href="{% url 'submit_sol_for_problem' submission.problem.number %}">
                        {% if submission.status == 'DNA' %}Upload solution{% else %}Re-upload solution{% endif %}
                    </a>{% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

templates/round/submit_sol_for_problem.html
{% extends "./base.html" %}

{% block head_title %}Submit a solution for {{ submission.problem }}{% endblock %}
{% block content_title %}Submit a solution for {{ submission.problem }}{% endblock %}

{% block content %}

<div class="row g-3 mb-3">
    <div class="col-md-auto">
        <div class="fw-light">Contestant ID</div>
        <div>{{ submission.contestant.contestant_id }}</div>
    </div>
    <div class="col-md-auto">
        <div class="fw-light">Contestant name</div>
        <div>{{ submission.contestant.fl_name }}</div>
    </div>
    <div class="col-md-auto">
        <div class="fw-light">Problem</div>
        <div>{{ submission.problem.number }}</div>
    </div>
    <div class="col-md-auto">
        <div class="fw-light">Current status</div>
        <div>{{ submission.get_status_display }}</div>
    </div>
    <div class="col-md-auto">
        <div class="fw-light">Last submitted (GMT):</div>
        <div>{{ submission.submission_time|date:"d N Y, H:i:s"|default:"--" }}</div>
    </div>
    {% if submission.status != 'DNA' %}
    <div class="col-md-12">
        <div class="fw-light">Current submission:</div>
        <div><a href="{{ submission.solution.url }}" target="_blank">
                {{ submission.solution.name|slice:"82:" }}</a></div>
    </div>
    {% endif %}
</div>


<form enctype="multipart/form-data" action="" method="post" onsubmit="disableSubmitInput()">
    {% csrf_token %}
    <!-- https://docs.djangoproject.com/en/3.1/topics/forms/#rendering-fields-manually -->
    <div class="mb-3">
        <label for="solutionInput" class="form-label fw-light">{{ form.solution.label }}</label>
        {{ form.solution }}
        <div class="form-text">{{ form.solution.help_text }}</div>
        {% if form.solution.errors %}
        <div id="solutionValidationFeeback" class="invalid-feedback">
            <ul class="list-unstyled mb-0">
                {% for error in form.solution.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
    </div>

    {% if form.non_field_errors %}
    <div class="mb-3 text-danger">
        <ul class="list-unstyled mb-0">
            {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <div class="row g-2 justify-content-md-end" dir="rtl">
        <div class="col-md-3" dir="ltr">
            <input type="submit" id="submitInput" class="btn btn-primary w-100" value="Submit">
        </div>
        <div class="col-md-2" dir="ltr">
            <a class="btn btn-secondary w-100" href="{% url 'submission_summary' %}">Go back</a>
        </div>
    </div>
</form>

<script>
    function disableSubmitInput() {
        var input = document.getElementById('submitInput');
        input.disabled = true;
        input.value = 'Uploading...';
    }
</script>

{% endblock %}